models/usuario.py
from utils import db
from flask_login import UserMixin

class Usuario(db.Model, UserMixin):
    __tablename__ = 'usuarios'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(100), nullable=False)
    senha = db.Column(db.String(100), nullable=False)

    def __init__(self, username, email, senha):
        self.username = username
        self.email = email
        self.senha = senha  

app.py
from flask import Flask, render_template, flash
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager,login_user, logout_user, login_required, current_user
from flask_migrate import Migrate
from controllers.usuario import bp_usuarios
from utils import db, lm

app = Flask(__name__, static_folder='static', static_url_path='/static')

app.config['SECRET_KEY'] = 'abuble'
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///dados.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.register_blueprint(bp_usuarios, url_prefix = '/usuarios')
migrate = Migrate(app, db)


db.init_app(app)
lm.init_app(app)

@app.route('/registrar')
def registrar():
    return render_template('pagina-registrar.html')

@app.route('/login')
def login():
    return render_template('pagina-login.html')

@app.route('/dashboard')
def dashboard():
    return render_template('futuro-dashboard.html')


if __name__ == '__main__':
    app.run()

controllers/usuario.py
from flask import render_template, request, redirect, flash, Blueprint
from models.usuario import Usuario
from utils import db, lm
import sqlalchemy as sa
from urllib.parse import urlsplit
from flask_login import login_user, logout_user, login_required
import hashlib


bp_usuarios = Blueprint("usuarios", __name__, template_folder='templates')

@lm.user_loader
def load_user(id):
	usuario = Usuario.query.filter_by(id = id).first()
	return usuario

@bp_usuarios.route('/usuario', methods=['POST'])
def create_usuario():
    username = request.form.get('username')
    email = request.form.get('email')
    senha = request.form.get('senha')
    senha_hash = hashlib.sha256(senha.encode())
    csenha = request.form.get('csenha')
    
    username_existente = Usuario.query.filter_by(username=username).first()
    if username_existente:
        flash('Nome de usuário já está em uso')
        return redirect('/registrar')
    
    if senha == csenha:
        usuario = Usuario(username, email, senha_hash.hexdigest())
        db.session.add(usuario)
        db.session.commit()
        flash ('Dados cadastrados com sucesso')
        return redirect('/entrar')
    else:
        flash ('Erro. Senhas não correspondentes')
        return redirect('/registrar')

@bp_usuarios.route('/auth_usuario', methods=['POST'])
def autenticar_usuario():
    login = request.form.get('login')
    senha = request.form.get('senha')

    user = Usuario.query.filter((Usuario.username == login) | (Usuario.email == login)).first()

    if user and user.senha == hashlib.sha256(senha.encode()).hexdigest():
        login_user(user)
        next_page = request.args.get('next')
        if not next_page or urlsplit(next_page).netloc != '':
            next_page = ('/dashboard')
        return redirect(next_page)
    
  
    flash('Usuário ou senha inválidos.', 'danger')
    return redirect('/entrar')

templates/futuro-dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <!-- bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- fontes -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    
    <!-- css -->
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">

</head>
<body class="body-entrar">
    <div class="d-flex align-items-center justify-content-center w-100 h-100">
        <h1 class="kanit fw-bold aviso"> A autenticação deu certo, mas não foram criadas mais telas</h1>
    </div>
</body>

templates/pagina-base-entrar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block titulo %} {% endblock %}</title>
    <!-- bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- fontes -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    
    <!-- css -->
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">

</head>
<body class="body-entrar">
    <section class="w-100 h-100">
        <div class="position-relative">
            <img class="onda-entrar position-absolute" src="/static/img/onda-superior-esquerdo.svg" alt="">
        </div>
        <div class="position-absolute bottom-0 end-0 z-index-1">
            <img class="onda-entrar" src="/static/img/onda-inferior-direito.svg" alt="">
        </div>
        {%block conteudo%}
        {%endblock%}
    </section>
</body>
</html>

templates/pagina-login.html
{%extends 'pagina-base-entrar.html'%}

{% block titulo %} 
    Login
{% endblock %}

{%block conteudo%}

<div class="d-flex flex-column conteudo-pag-login gap-4 align-items-center justify-content-center w-100 h-100 row">
    <div class="d-flex flex-column align-items-center justify-content-center col-4 gap-3">
        <img src="/static/img/Logo.svg" alt="" class="logo-entrar">
        <h1 class="kanit entre-conta fw-bold">Entre em Icevania!</h1>
    </div>
    <div class="forms-login p-3 col-4">
        <form method='post' action="{{url_for('usuarios.autenticar_usuario')}}" class="d-flex flex-column p-2 gap-2">
            <label for="login" class="text-light">Usuário ou e-mail</label>
            <input type="text" id="login" name="login" required class="rounded border-0 p-2 text-light" placeholder="Usuário ou e-mail">
        
            <div class="d-flex flex-column password-container position-relative">
                <label for="senha" class="text-light">Senha</label>
                <input type="password" id="senha" name="senha" required class="rounded border-0 p-2 text-light" placeholder="Digite a senha">
                <img src="/static/img/olho-fechado.png" id="toggleSenha" class="toggle-password position-absolute top-50" data-input="senha" alt="Ver senha">
            </div>
            <a href="#" class="azulzinho esqueceu-senha d-flex w-100 justify-content-end">Esqueceu a senha?</a>

            <input type="submit" value="Entrar" class="botao_registrar border-0 rounded text-light fw-bold kanit mt-3">
        </form>
        <div class="naptemconta d-flex gap-1 justify-content-end w-100 pe-2">
            <p class="text-light">Não tem uma conta?</p>
            <a href="/registrar" class="azulzinho">Registre-se</a>
        </div>
    </div>
</div>

<script src="/static/js/script.js"></script>

{%endblock%}

templates/pagina-registrar.html
{%extends 'pagina-base-entrar.html'%}

{% block titulo %} 
    Registre-se
{% endblock %}

{%block conteudo%}
    <div class="conteudo-pag-registrar align-items-center justify-content-center w-100 h-100 row">
        <div class="d-flex flex-column align-items-center justify-content-center col-4">
            <img src="/static/img/Logo.svg" alt="">
            <h1 class="kanit crie-conta fw-bold">Crie sua conta!</h1>
        </div>
        <div class="col-4 d-flex flex-column gap-3 align-items-center justify-content-center h-100">
            {% set mensagens = get_flashed_messages() %} 
            {% if mensagens %}     
                <div id = "flash-message" class='alert alertbg text-light fw-bold d-flex justify-content-center m-0' role="alert">
                    {% for msg in mensagens %}
                        {{ msg }}
                    {% endfor %}
                </div>
            {% endif %}
            <h2 class="kanit fw-bold m-0">Registre-se em Icevania!</h2>
            <form method='post' action="{{url_for('usuarios.create_usuario')}}" class="d-flex flex-column gap-2 w-100"> 
                <label for="username" class="text-light">Nome de usuário</label>
                <input type="text" id="username" name="username" required class="rounded border-0 p-2 text-light" placeholder="Usuário">

                <label for="email" class="text-light">Email</label>
                <input type="email" id="email" name="email" required class="rounded border-0 p-2 text-light" placeholder="fulaninho@email.com">
                
                <div class="d-flex flex-column password-container position-relative">
                    <label for="senha" class="text-light">Senha</label>
                    <input type="password" id="senha" name="senha" required class="rounded border-0 p-2 text-light" placeholder="Digite a senha">
                    <img src="/static/img/olho-fechado.png" id="toggleSenha" class="toggle-password position-absolute top-50" data-input="senha" alt="Ver senha">
                </div>
                
                <div class="d-flex flex-column password-container position-relative">
                    <label for="csenha" class="text-light">Confirmar Senha</label>
                    <input type="password" id="csenha" name="csenha" required class="rounded border-0 p-2 text-light" placeholder="Confirme a senha">
                    <img src="/static/img/olho-fechado.png" id="toggleSenha" class="toggle-password position-absolute top-50" data-input="csenha" alt="Ver senha">
                </div>
                
                <input type="submit" value="Registrar" class="botao_registrar position-relative border-0 rounded text-light fw-bold kanit mt-3">
            </form>
            <div class="jatemconta d-flex gap-1 pt-2 justify-content-end w-100 position-relative z-index-2">
                <p class="text-light">Já tem uma conta?</p>
                <a href="/login" class="azulzinho">Entrar</a>
            </div>
        </div>
    </div>
    <script src="/static/js/script.js"></script>
    
{%endblock%}